name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  test:
    uses: rajilingam/reusableworkflow/.github/workflows/Test Reusable Workflow.yml@main
    with:
      input1: value1
      input2: value2
    secrets:
      secret1: ${{ secrets.SECRET1 }}
      secret2: ${{ secrets.SECRET2 }}
