name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  test:
    uses: rajilingam/reusableworkflow/.github/workflows/test-reusable-workflow.yml@master
    with:
      input1: "raji"  # Replace with actual value
      input2: "lingam"  # Optional, can be omitted
    secrets:
      secret1: ${{ secrets.SECRET1 }}  # Ensure this secret exists
      secret2: ${{ secrets.SECRET2 }}  # Optional, ensure this secret exists if used

      
