name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  test:
    uses: ORG_NAME/repo-name/.github/workflows/test-reusable-workflow.yml@master
    with:
      input1: value1
      input2: value2
    secrets:
      secret1: ${{ secrets.SECRET1 }}
      secret2: ${{ secrets.SECRET2 }}
