name: Caller Workflow

on: 
  # can be ran manually
  workflow_dispatch:

jobs:

  test:
    # call the Reusable Workflow file
    uses: rajilingam/reusableworkflow/.github/workflows/test-reusable.yml@main
